/**
 * The main content of the resume
 */
const content = {
  name: "Stephen Shelton",
  phone: "214.535.5783",
  email: "steve@brewcraft.org",
  location: "Colorado Springs / Denver",
  linkedin: {
    link: "https://www.linkedin.com/in/notlesh/",
    short: "linkedin.com/in/notlesh/",
  },
  github: {
    link: "https://github.com/notlesh",
    short: "github.com/notlesh",
  },
  description: "Diverse engineer with 15 years of professional experience across many industries and programming environments. Thorough and dependable with a preference for thoughtful and maintainable code.",
  languages: [
    {name: "C++", strength: 0.9, },
    {name: "Java", strength: 0.85, },
    {name: "JavaScript", strength: 0.85, },
    {name: "Python", strength: 0.75, },
    {name: "SQL", strength: 0.7, },
    {name: "Solidity", strength: 0.65, },
  ],
  technologies: [
    {name: "Linux", strength: 0.9, },
    {name: "Git", strength: 0.9, },
    {name: "Blockchain", strength: 0.85, },
    {name: "Cryptography", strength: 0.8, },
    {name: "Networking", strength: 0.8, },
    {name: "Android", strength: 0.75, },
    // {name: "Cloud Compute", strength: 0.75, },
  ],
  techniques: [
    {name: "OO Design", strength: 0.9, },
    {name: "Multithreading", strength: 0.9, },
    {name: "Documentation", strength: 0.9, },
    {name: "Optimization", strength: 0.9, },
    {name: "Debugging", strength: 0.9, },
    {name: "Test Cases", strength: 0.85, },
    {name: "APIs/REST", strength: 0.75, },
  ],
  roles: [
    { start: "September 2019",
      end: "Present",
      org: "Loki Network",
      title: "Software Engineer",
      points: [
        "<i>Lokinet is an onion-routing privacy network which rewards network operators via blockchain-based incentives.</i>",
        "Contributed to multi-layer P2P onion-routing protocol stack",
        "Devised key-blinding scheme which allows for public DHT storage of semi-private routing information",
        "Optimized DHT recursion technique for efficiency and privacy",
        "Designed incentive models for adversarial environments",
        "Wrote technical portions of white and yellow papers",
        "Maintained control panel GUI project / github repository",
        "Collaborated on Python-based loopback testnet which can simulate hundreds of network actors simultaneously",
        "<i>Lokinet is entirely open source, find it at <a href='https://github.com/loki-project/loki-network'>https://github.com/loki-project/loki-network</a></i>.",
      ],
    },
    { start: "January 2010",
      end: "Present",
      org: "Brewcraft Software",
      title: "President",
      points: [
        "Created an open source electric beer-brewing system complete with a backend server, RPC API, and web UI",
        "Participated in Ethereum DApps/Hackathons",
        "Developed full 3D game engine from the ground up, capable of running on multiple platforms (Android, Linux, Windows)",
        "Designed automated cryptocurrency trading bots",
        "Implemented algorithms for shape recognition to track live objects and optimized to run at video framerate",
        "Created custom, multi-platform UI framework to take advantage of OpenGL hardware acceleration",
      ],
    },
    { start: "January 2018",
      end: "April 2019",
      org: "Arrow Electronics",
      title: "IoT Software Engineer",
      points: [
        "Implemented cellular modem driver for MBED OS",
        "Used REST API to publish IoT device telemetry on multiple technology stacks",
        "Assisted in debugging both server- and client-side REST APIs",
        "Designed cellular connectivity strategy to achieve sub-MB/month data usage restriction for smart watercooler",
        "Improved the resiliency and efficiency of existing products to help deliver on customer expectations",
        "Assisted in project planning and estimations, development scheduling, and system architecture",
        "Created demos and Proof-of-Concepts to help illustrate the group’s abilities to customers",
        "Designed guidelines for technical interviewing and onboarding",
        "Acted as mentor to junior staff",
      ],
    },
    { start: "March 2015",
      end: "January 2018",
      org: "Netscout",
      title: "Lead Software Engineer",
      points: [
        "Led development team in design, implementation, and support of NetScout’s AirCheck G2, a handheld WiFi diagnostic tool which provides detailed information about WiFi networks and basic RF measurements",
        "Designed JSON-RPC communication strategy for inter-process communication",
        "Assisted in design and implementation of an Android framework designed to provide consistent REST-API integration across multiple next-gen products",
        "Participated in product planning, feature risk assessment, prioritization, and deliverables",
        "Oversaw product testing and measurement characterization efforts",
        "Provided technical guidance for WiFi, Bluetooth, and USB certifications in multiple countries",
        "Designed automated tests to detect assembly failures in the manufacturing process",
        "Maintained specialized Linux kernel, U-Boot, and WiFi driver forks",
        "Guided intern \"pet projects\"",
        "Participated in legal and licensing policy",
      ],
    },
    { start: "January 2012",
      end: "March 2015",
      org: "Solmirus",
      title: "Systems Engineer",
      points: [
        "Developed the ASIVA (All Sky Infrared & Visible Analyzer), an imaging and analysis instrument capable of running autonomously and reliably in all weather conditions while processing gigabytes of image data per hour",
        "Implemented high performance TCP message bus with guaranteed message delivery, providing a very simple asynchronous API",
        "Created code generation tool (partially open-sourced) to produce consistent code for data objects and other boilerplate components which could operate in multiple programming languages",
        "Provided simple REST API for 3rd parties to extract acquisition data",
        "Wrote extensive end-user documentation on usage, maintenance, and troubleshooting",
        "Created product assembly, testing, transportation, and installation guidelines",
      ],
    },
    { start: "February 2011",
      end: "January 2012",
      org: "Group Systems",
      title: "Sr. Software Engineer",
      points: [
        "Built the next-gen version of ThinkTank, a collaboration tool used around the globe by successful businesses and governments such as NASA, Raytheon, Procter & Gamble, and IBM",
        "Designed and implemented AJAX based message bus to create a robust User Interface with “installed-app” feel",
        "Used tools such as profilers to analyze and prepare for performance scaling issues between numerous browsers",
        "Improved legacy software to extend product lifetime, providing the organization the opportunity to develop next-gen software",
      ],
    },
    { start: "August 2006",
      end: "December 2010",
      org: "Intrameta Corporation",
      title: "Software Engineer",
      points: [
        "Developed BOSS, a hosted operations support systems (OSS). BOSS was used by many regional telecoms, ISPs, and service centers to provide device management (DHCP, RADIUS), trouble ticketing, provisioning, and customer data hosting (e-mail, website, and FTP).",
        "Implemented client and server software for protocols based on RFCs including HTTP, DHCP, SMTP, FTP, POP and IMAP",
        "Led design of an end-to-end encrypted email server to meet emerging industry encryption requirements",
        "Designed and implemented web UI using custom-built web framework",
        "Created code generation tools to automate creation of data model objects",
        "Maintained software releases, production and staging environments, and data center hardware",
        "Initialized and maintained Amazon EC2-based cloud servers and migrated services from physical servers",
      ],
    },
  ],
  education: [
    { start: "2005",
      end: "2006",
      text: "Internship at Intrameta Corporation",
    },
    { start: "2004",
      end: "2005",
      text: "Studied Computer Science (University of North Texas)",
    },
  ],
  extraEnd: [
    { headline: "Note about this resume",
      /* note that this is passed through html-react-parser, and is susceptible to injection attacks */
      body: "This resume was created with ReactJS (Javascript/HTML/CSS). See the related github repo at <a href='https://github.com/notlesh/stephen-shelton-resume'>https://github.com/notlesh/stephen-shelton-resume</a> for more info.",
    },
  ],
};

export default content;
